development:
  enabled: false
  api_key: "token"
  list_id: "token"

production:
  enabled: false
  api_key: "token"
  list_id: "token"

test:
  enabled: false
  api_key: "test_api_token"
  list_id: "test_list_token"

  second_list_id: "second_list_token"

